/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Shoe(props) {
  const { nodes, materials } = useGLTF("/model/AirMaxOneFinal.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sock.geometry}
        material={materials["Material Sock"]}
        position={[0, 1.073, -1.141]}
        scale={[0.527, 0.149, 0.149]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sole.geometry}
        material={materials["Material.002"]}
        position={[0, 1.073, -1.141]}
        scale={[0.527, 0.149, 0.149]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.BulleDair.geometry}
        material={materials["Material Bulle dair"]}
        position={[0, 1.073, -1.141]}
        scale={[0.527, 0.149, 0.149]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SoleTrim.geometry}
        material={materials["Material.Sole Trim"]}
        position={[0, 1.073, -1.141]}
        scale={[0.527, 0.149, 0.149]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.tread.geometry}
        material={materials["Material Tread"]}
        position={[0, 1.073, -1.141]}
        scale={[0.527, 0.149, 0.149]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.treadtop.geometry}
        material={materials.Material}
        position={[0, 1.073, -1.141]}
        scale={[0.527, 0.149, 0.149]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sock001.geometry}
        material={materials["Material.001"]}
        position={[0, 0.123, 0]}
        scale={[0.527, 0.149, 0.149]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sock002.geometry}
        material={materials["Material.004"]}
        position={[0, 1.073, -1.141]}
        scale={[0.527, 0.149, 0.149]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sock003.geometry}
        material={materials["Material.005"]}
        position={[0, 1.073, -1.141]}
        scale={[0.527, 0.149, 0.149]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sock_back.geometry}
        material={materials["Material Sock Back"]}
        position={[0, 1.073, -1.141]}
        scale={[0.527, 0.149, 0.149]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Logo_Nike.geometry}
        material={materials["Material Logo Nike"]}
        position={[0, 0.123, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Languette.geometry}
        material={materials["Material languette"]}
        position={[0, 0.179, 0]}
        scale={[0.527, 0.149, 0.14]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Etoile.geometry}
        material={materials["Material.007"]}
        position={[0, 0.05, 0.011]}
        scale={[1.151, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.CinqEtoiles.geometry}
        material={materials["Material.007"]}
        position={[0, 0.05, 0]}
      />
      <group
        position={[3.055, 1.046, -1.978]}
        rotation={[-Math.PI / 2, Math.PI / 2, 0]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane003.geometry}
          material={materials["Material.008"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane003_1.geometry}
          material={materials["Material.009"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane003_2.geometry}
          material={materials["Material.010"]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["lions-indomptables-cameroun-229674"].geometry}
        material={materials["lions-indomptables-cameroun-229674"]}
        position={[0, 1.999, 0]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sock004.geometry}
        material={materials["Material Sock.002"]}
        position={[0, 1.073, -1.141]}
        scale={[0.527, 0.149, 0.149]}
      />
    </group>
  );
}

useGLTF.preload("/model/AirMaxOneFinal.glb");
