/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Auteur: Nguidjol Derrick
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Banlieue(props) {
  const { nodes, materials } = useGLTF("/model/Banlieue94.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.traffic_cone_02.geometry}
        material={materials["Plastic Orange"]}
        position={[1.901, 1.711, 3.645]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={1.129}
      >
        <meshBasicMaterial color="orange"/>
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.crowd_control_barrier_Cylinder005.geometry}
        material={materials["Metallic Acier"]}
        position={[0.51, 1.702, 3.758]}
        rotation={[Math.PI / 2, 0, -0.536]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle002.geometry}
        material={materials["Material.021"]}
        position={[0, 1.276, 0]}
        scale={0.046}
      />
      <group
        position={[0.62, 6.463, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[1.001, 0.617, 0.19]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane_1.geometry}
          material={materials["Material.004"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane_2.geometry}
          material={materials["Material.005"]}
        />
      </group>
      <group
        position={[-0.666, 5.935, 0]}
        rotation={[-Math.PI / 2, 0, -Math.PI]}
        scale={[1.001, 0.617, 0.19]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane001_1.geometry}
          material={materials["Material.004"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane001_2.geometry}
          material={materials["Material.005"]}
        />
      </group>
      <group
        position={[-0.666, 5.378, 0]}
        rotation={[-Math.PI / 2, 0, -Math.PI]}
        scale={[1.001, 0.617, 0.19]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane002_1.geometry}
          material={materials["Material.004"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane002_2.geometry}
          material={materials["Material.005"]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle003.geometry}
        material={materials["Material.020"]}
        position={[-1.419, 1.675, 0.788]}
        scale={[0.073, 0.024, 0.073]}
      />
      <group
        position={[-1.414, 3.596, 0.853]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.452, 0.264, 0.589]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane003_1.geometry}
          material={materials["Material.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane003_2.geometry}
          material={materials["Material.003"]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane004.geometry}
        material={materials["Material.002"]}
        position={[-1.414, 3.596, 0.719]}
        rotation={[Math.PI / 2, 0, Math.PI]}
        scale={[0.452, 0.267, 0.589]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.uploads_files_4087435_Sewer_door_01.geometry}
        material={materials.lambert2SG}
        position={[-2.423, 1.717, 2.204]}
        rotation={[Math.PI / 2, 0, -0.816]}
        scale={0.023}
      />
      <group
        position={[-2.991, 1.669, 0.569]}
        rotation={[Math.PI / 2, 0, -1.572]}
        scale={1.918}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.folding_chair_02001_1.geometry}
          material={materials["Material.007"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.folding_chair_02001_2.geometry}
          material={materials["Material.006"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.folding_chair_02001_3.geometry}
          material={materials["Material.018"]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.traffic_cone_02001.geometry}
        material={materials["Plastic Orange"]}
        position={[1.901, 1.711, 2.825]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={1.129}
      >
        <meshBasicMaterial color="orange" />
      </mesh>
      <group
        position={[1.506, 1.716, -1.503]}
        rotation={[Math.PI / 2, 0, -2.978]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Box_12in_Plane002_1.geometry}
          material={materials["Material.022"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Box_12in_Plane002_2.geometry}
          material={materials.CardBoardExterior}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Box_12in_Plane002_3.geometry}
          material={materials.PizzaHut}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.cardboard_box_02.geometry}
        material={materials.Material}
        position={[3.208, 1.69, -1.698]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={1.427}
      >
        <meshBasicMaterial color="brown" />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane006.geometry}
        material={materials["Material.011"]}
        position={[0.921, 6.408, 0.097]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.126}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane008.geometry}
        material={materials["Material.016"]}
        position={[-1.415, 3.593, 0.936]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.404, 0.146, 0.146]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane009.geometry}
        material={materials["Material.017"]}
        position={[-1.414, 3.596, 0.846]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.452, 0.264, 0.589]}
      />
      <group
        position={[-2.596, 1.669, -1.274]}
        rotation={[Math.PI / 2, 0, -0.641]}
        scale={1.918}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.folding_chair_02002_1.geometry}
          material={materials["Material.007"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.folding_chair_02002_2.geometry}
          material={materials["Material.006"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.folding_chair_02002_3.geometry}
          material={materials["Material.018"]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane010.geometry}
        material={materials["Material.023"]}
        position={[-1.479, 3.935, 0.948]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.137}
      />
      <group
        position={[-1.444, 4.76, 0.981]}
        rotation={[1.746, 0, 0]}
        scale={[0.545, 0.347, 0.347]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane011_1.geometry}
          material={materials["Material.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane011_2.geometry}
          material={materials["Material.010"]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane012.geometry}
        material={materials["Material.002"]}
        position={[-1.444, 4.76, 0.516]}
        rotation={[1.397, 0, 0]}
        scale={[0.545, 0.347, 0.347]}
      />
      <group
        position={[-1.996, 4.76, 0.787]}
        rotation={[Math.PI / 2, 0.191, -Math.PI / 2]}
        scale={[0.255, 0.347, 0.347]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane013_1.geometry}
          material={materials["Material.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane013_2.geometry}
          material={materials["Material.024"]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane014.geometry}
        material={materials["Material.002"]}
        position={[-1.005, 4.76, 0.787]}
        rotation={[Math.PI / 2, -0.193, -Math.PI / 2]}
        scale={[0.255, 0.347, 0.347]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Text.geometry}
        material={nodes.Text.material}
        position={[-1.599, 4.891, 1.075]}
        rotation={[1.745, 0, 0]}
        scale={0.143}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Text001.geometry}
        material={nodes.Text001.material}
        position={[-1.778, 4.655, 1.05]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.113}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane015.geometry}
        material={materials["Material.025"]}
        position={[-1.965, 4.727, 0.785]}
        rotation={[Math.PI, 0, 1.379]}
        scale={[0.099, 0.123, 0.123]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane016.geometry}
        material={materials["Material.028"]}
        position={[-2.014, 4.923, 0.785]}
        rotation={[Math.PI, 0, 1.379]}
        scale={[0.099, 0.123, 0.123]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.dial_01.geometry}
        material={materials["Material.006"]}
        position={[-0.993, 1.701, -1.747]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={1.133}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.dial_02.geometry}
        material={materials["Material.006"]}
        position={[-0.993, 1.701, -1.747]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={1.133}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.dial_03.geometry}
        material={materials["Material.006"]}
        position={[-0.993, 1.701, -1.747]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={1.133}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.screen.geometry}
        material={materials["Material.012"]}
        position={[-0.993, 1.701, -1.747]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={1.133}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.knob_01.geometry}
        material={materials["Material.006"]}
        position={[-0.993, 1.701, -1.747]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={1.133}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.knob_02.geometry}
        material={materials["Material.006"]}
        position={[-0.993, 1.701, -1.747]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={1.133}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.retro_tv_body.geometry}
        material={materials.Plastic_Black}
        position={[-0.993, 1.701, -1.747]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={1.133}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Le.geometry}
        material={materials["Material.005"]}
        position={[-0.197, 5.845, 0.083]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.092}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Orly.geometry}
        material={materials["Material.005"]}
        position={[-0.312, 6.366, 0.083]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.327}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Roi.geometry}
        material={materials["Material.005"]}
        position={[-0.099, 5.849, 0.083]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.28}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Secriture.geometry}
        material={materials["Material.005"]}
        position={[-0.46, 5.341, 0.083]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.092}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Seine.geometry}
        material={materials["Material.005"]}
        position={[-0.35, 5.284, 0.083]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.297}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Barre.geometry}
        material={materials["Material.005"]}
        position={[-0.43, 5.31, 0.083]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.207}
      />
      <group
        position={[2.219, 1.705, -1.567]}
        rotation={[Math.PI / 2, 0, 1.687]}
        scale={0.021}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.uploads_files_2073206_Trash_Container_obj_.geometry}
          material={materials.TC_plastic_green}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.uploads_files_2073206_Trash_Container_obj__1.geometry}
          material={materials.Plastic_Black}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.uploads_files_2073206_Trash_Container_obj__2.geometry}
          material={materials["Material.026"]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Vitry.geometry}
        material={materials["Material.005"]}
        position={[-1.129, 5.284, 0.083]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.297}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Choisy.geometry}
        material={materials["Material.005"]}
        position={[-1.04, 5.849, 0.083]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.28}
      />
    </group>
  );
}

useGLTF.preload("/model/Banlieue94.glb");
