/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function FisherPrice(props) {
  const { nodes, materials } = useGLTF("/model/FisherPrice.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube.geometry}
        material={materials["Material.001"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube001.geometry}
        material={materials["Black Plastic"]}
        position={[0.756, 2.231, 0.515]}
        scale={[0.899, 0.719, 0.824]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube002.geometry}
        material={materials["Black Plastic"]}
        position={[0.756, 2.231, 0.099]}
        scale={[0.899, 0.719, 0.824]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube003.geometry}
        material={materials["Black Plastic"]}
        position={[0.756, 2.231, -0.318]}
        scale={[0.899, 0.719, 0.824]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube004.geometry}
        material={materials["Black Plastic"]}
        position={[0.756, 2.231, -0.738]}
        scale={[0.899, 0.719, 0.824]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube005.geometry}
        material={materials["Black Plastic"]}
        position={[0.756, 2.231, -1.159]}
        scale={[0.899, 0.719, 0.824]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle.geometry}
        material={materials["Material.001"]}
        position={[0.002, 2, -1.922]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[0.549, 0.701, 0.549]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle001.geometry}
        material={materials.Black}
        position={[0.002, 2, -1.939]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[0.478, 0.671, 0.478]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle002.geometry}
        material={materials["Material.002"]}
        position={[0.002, 2, -1.939]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[0.412, 0.579, 0.412]}
      />
      <group
        position={[0.434, 1.299, 2.156]}
        rotation={[0.138, -1.193, 0]}
        scale={[0.194, 0.49, 0.194]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder_1.geometry}
          material={materials["Material.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder_2.geometry}
          material={materials["Black Plastic"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder_3.geometry}
          material={materials["Material.006"]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder001.geometry}
        material={materials["Black Plastic"]}
        position={[0.434, 1.299, 2.156]}
        rotation={[0.138, -1.193, 0]}
        scale={[0.194, 0.49, 0.194]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane.geometry}
        material={materials["Material.002"]}
        position={[0.756, 2.536, 0.496]}
        rotation={[0, 0, -Math.PI / 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere001.geometry}
        material={materials["Material.007"]}
        position={[0.679, 2.681, 1.212]}
        scale={0.045}
      />
      <group position={[0.691, 2.536, 0.496]} rotation={[0, 0, -Math.PI / 2]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane005_1.geometry}
          material={materials["Material.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane005_2.geometry}
          material={materials.Black}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane002.geometry}
        material={materials["Material.003"]}
        position={[0.756, 2.536, 0.496]}
        rotation={[0, 0, -Math.PI / 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Copyright.geometry}
        material={materials.Black}
        position={[0.731, 0.26, -0.47]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.056}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.FisherPrice.geometry}
        material={materials.Black}
        position={[0.739, 0.172, 0.414]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[0.206, 0.197, 0.197]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Vert002.geometry}
        material={materials.Black}
        position={[-0.019, 1.985, 1.84]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Vert005.geometry}
        material={materials.Black}
        position={[0.61, 0.705, 2.403]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane004.geometry}
        material={materials.Black}
        position={[0.699, 2.695, -0.118]}
      />
      <group position={[0.513, 2.695, -0.118]} rotation={[0, 0, -0.152]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane006.geometry}
          material={materials["Material.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane006_1.geometry}
          material={materials["Material.004"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane006_2.geometry}
          material={materials["Material.005"]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Text002.geometry}
        material={materials.Black}
        position={[0.723, 2.687, 0.818]}
        rotation={[Math.PI / 2, 0.843, -Math.PI / 2]}
        scale={[0.051, 0.051, 0.043]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder002.geometry}
        material={materials.Black}
        position={[0.596, 1.229, -0.117]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane008.geometry}
        material={materials["Material.005"]}
        position={[-0.332, 3.168, -0.008]}
        rotation={[0, 0, -0.112]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane009.geometry}
        material={materials["Material.005"]}
        position={[-0.332, 3.314, -0.008]}
        rotation={[0, 0, -0.112]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane010.geometry}
        material={materials["Material.002"]}
        position={[-0.069, 3.271, -0.008]}
        scale={0.956}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane011.geometry}
        material={materials["Material.006"]}
        position={[1.385, 1.224, -0.447]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[0.108, 0.163, 0.163]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle003.geometry}
        material={materials["Material.004"]}
        position={[0.235, 2.994, -0.952]}
        rotation={[0, 0, -0.703]}
        scale={0.125}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle004.geometry}
        material={materials["Material.004"]}
        position={[0.552, 0.453, -0.008]}
        scale={[0.247, 0.308, 0.308]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Text003.geometry}
        material={materials["Material.002"]}
        position={[0.461, 1.993, -2.034]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.164}
      />
      <group position={[-5.896, 1.181, -4.78]} rotation={[0, 0.182, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube006.geometry}
          material={materials.Bois}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube006_1.geometry}
          material={materials["Material.008"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube006_2.geometry}
          material={materials.Material}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Text.geometry}
        material={materials.Ecriteaux}
        position={[-4.606, 5.566, 1.977]}
        rotation={[Math.PI / 2, 0, -1.753]}
        scale={0.229}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Text001.geometry}
        material={materials.Ecriteaux}
        position={[-4.349, 5.038, 3.18]}
        rotation={[Math.PI / 2, 0, -1.753]}
        scale={[0.131, 0.121, 0.121]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane012.geometry}
        material={materials["Material.001"]}
        position={[1.046, 0.648, 1.669]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[0.552, 0.943, 0.943]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Text005.geometry}
        material={materials["Material.001"]}
        position={[1.067, 0.765, 2.1]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[0.194, 0.186, 0.186]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane014.geometry}
        material={materials["Material.002"]}
        position={[1.599, 0.451, 1.669]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={0.943}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Text006.geometry}
        material={materials["Material.001"]}
        position={[1.067, 0.351, 2.131]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.127}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Side1.geometry}
        material={materials["Material.001"]}
        position={[1.071, 0.621, 1.669]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.102}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Vis.geometry}
        material={materials["Material.006"]}
        position={[1.032, 1.139, 2.552]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[0.115, 0.129, 0.115]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Text004.geometry}
        material={materials["Material.001"]}
        position={[1.059, 0.848, 1.267]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.053}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Vert006.geometry}
        material={materials.Black}
        position={[-0.02, -0.46, 1.978]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[0.369, 0.151, 0.369]}
      />
    </group>
  );
}

useGLTF.preload("/model/FisherPrice.glb");
