/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
By Nguidjol Derrick
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Room(props) {
  const { nodes, materials } = useGLTF("/model/Room.glb");
  return (
    <group {...props} dispose={null}>
      <group position={[0, 1.476, 0]} rotation={[-1.757, 0.061, 2.835]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial.geometry}
            material={materials.DefaultMaterial}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial001.geometry}
            material={materials.DefaultMaterial}
          />
        </group>
      </group>
      <group position={[0.583, 1.345, -2.817]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_0.geometry}
          material={materials.wire_000000000}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_1.geometry}
          material={materials.wire_028089177}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_5.geometry}
          material={materials.wire_000000000}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh_6.geometry}
          material={materials.wire_007007007}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sol001.geometry}
        material={materials["Material.031"]}
        position={[-0.037, 0.671, 0.91]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mur001.geometry}
        material={materials.WallMaterial}
        position={[-0.037, 3.587, -3.331]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mur002.geometry}
        material={materials.WallMaterial}
        position={[-4.27, 4.515, 0.897]}
        rotation={[0, 0, -Math.PI / 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Fenetre.geometry}
        material={materials.WallMaterial}
        position={[-4.273, 3.475, 2.817]}
        rotation={[0, 0, -Math.PI / 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tapis.geometry}
        material={materials["Material.032"]}
        position={[0.642, 0.694, 0.431]}
        rotation={[0, 1.564, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Fenetre001.geometry}
        material={materials.plastersubstance001}
        position={[-4.266, 3.473, 2.815]}
        rotation={[0, 0, -Math.PI / 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Canape001.geometry}
        material={materials["Default OBJ.006"]}
        position={[0.913, 2.705, 1.015]}
        rotation={[0, Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Canape002.geometry}
        material={materials["Default OBJ.006"]}
        position={[-1.294, 2.705, 1.015]}
        rotation={[0, Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Canape003.geometry}
        material={materials["Default OBJ.006"]}
        position={[0.913, 2.492, 1.015]}
        rotation={[0, Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Canape004.geometry}
        material={materials["Default OBJ.006"]}
        position={[-3.459, 2.492, 1.015]}
        rotation={[0, Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Canape005.geometry}
        material={materials["Default OBJ.006"]}
        position={[0.913, 3.925, 1.015]}
        rotation={[0, Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.PiedCanape.geometry}
        material={materials["Noir-2"]}
        position={[0.913, 2.253, 1.015]}
        rotation={[0, Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.PiedCanape002.geometry}
        material={materials["Noir-2"]}
        position={[-3.283, 2.253, 1.015]}
        rotation={[0, Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.PiedCanape003.geometry}
        material={materials["Noir-2"]}
        position={[-3.283, 2.253, 2.755]}
        rotation={[0, Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.PiedCanape004.geometry}
        material={materials["Noir-2"]}
        position={[0.904, 2.253, 2.755]}
        rotation={[0, Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube007.geometry}
        material={materials["Material.009"]}
        position={[0.472, 0.555, 2.98]}
        rotation={[0, Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube008.geometry}
        material={materials["Material.009"]}
        position={[4.409, 0.555, 2.98]}
        rotation={[0, Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube009.geometry}
        material={materials["Material.009"]}
        position={[0.472, -0.082, 2.98]}
        rotation={[0, Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.MeubleTv001.geometry}
        material={materials["Material.009"]}
        position={[0.472, 0.555, 2.98]}
        rotation={[0, Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane003.geometry}
        material={materials["Material.020"]}
        position={[6.385, 2.493, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane028.geometry}
        material={materials["Noir-2"]}
        position={[-3.695, 0.892, 0.667]}
        rotation={[Math.PI, -1.564, Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane029.geometry}
        material={materials["Noir-2"]}
        position={[-3.678, 0.892, -1.722]}
        rotation={[Math.PI, -1.564, Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane030.geometry}
        material={materials["Noir-2"]}
        position={[-3.744, 0.93, 0.666]}
        rotation={[Math.PI, -1.564, Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane166.geometry}
        material={materials["Noir-2"]}
        position={[-3.727, 0.93, -1.721]}
        rotation={[Math.PI, -1.564, Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane167.geometry}
        material={materials["Noir-2"]}
        position={[-3.44, 2.133, -0.604]}
        rotation={[Math.PI, -1.564, Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane168.geometry}
        material={materials["Noir-2"]}
        position={[-3.655, 2.235, -0.518]}
        rotation={[Math.PI, -1.564, Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane256.geometry}
        material={materials["Noir-2"]}
        position={[-3.476, 0.892, -0.436]}
        rotation={[Math.PI, -1.564, Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube_Cube001.geometry}
        material={materials.SofaCloth}
        position={[-1.718, 1.967, 4.295]}
        rotation={[Math.PI / 2, -0.493, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube_Cube002.geometry}
        material={materials.SofaCloth}
        position={[-1.178, 1.967, 3.978]}
        rotation={[1.821, -0.43, 0.551]}
      />
      <group
        position={[-3.92, 2.231, 0.468]}
        rotation={[Math.PI / 2, 0, -2.062]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.computer_screen_Cube009_1.geometry}
          material={materials["Default OBJ.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.computer_screen_Cube009_2.geometry}
          material={materials["0.003922_0.003922_0.003922_0.000000"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.computer_screen_Cube009_3.geometry}
          material={materials.materialscreen}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tv001.geometry}
        material={materials["Noir-2"]}
        position={[0.547, 1.978, -2.838]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tv002.geometry}
        material={materials["Noir-2"]}
        position={[0.563, 2.122, -2.859]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tv003.geometry}
        material={materials["Noir-2"]}
        position={[0.568, 3.077, -2.681]}
        rotation={[1.554, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tv004.geometry}
        material={materials["Material.002"]}
        position={[0.568, 3.077, -3.72]}
        rotation={[1.554, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Table001.geometry}
        material={nodes.Table001.material}
        position={[0.969, 0.292, 0.433]}
        rotation={[0, 1.564, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Table002.geometry}
        material={materials["Material.033"]}
        position={[0.642, 2.236, 0.431]}
        rotation={[0, 1.564, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Table003.geometry}
        material={materials["blanc mat"]}
        position={[1.005, 1.249, 0.437]}
        rotation={[0, 0.886, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Table004.geometry}
        material={materials["Material.033"]}
        position={[0.36, 1.382, 0.18]}
        rotation={[-Math.PI, 0.907, -Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder011.geometry}
        material={materials["Material.009"]}
        position={[2.891, 0.892, 0.781]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder024.geometry}
        material={materials.aluminium}
        position={[2.891, 0.892, 0.781]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder025.geometry}
        material={materials.aluminium}
        position={[2.891, 0.416, 0.781]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder009.geometry}
        material={materials["Material.009"]}
        position={[2.891, 0.892, 0.781]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder010.geometry}
        material={materials.aluminium}
        position={[2.891, 0.892, 0.781]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Siege001.geometry}
        material={materials["Material.Chair"]}
        position={[-2.467, 1.593, -0.547]}
        rotation={[Math.PI, -1.564, Math.PI]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle.geometry}
          material={materials.aluminium}
          position={[0, -0.516, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle001.geometry}
          material={materials.aluminium}
          position={[0.011, -0.478, 0.015]}
          rotation={[0, 1.257, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle002.geometry}
          material={materials.aluminium}
          position={[0, -0.478, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle003.geometry}
          material={materials.aluminium}
          position={[0.029, -0.478, 0.01]}
          rotation={[-Math.PI, Math.PI / 5, -Math.PI]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle004.geometry}
          material={materials.aluminium}
          position={[0.029, -0.478, -0.01]}
          rotation={[Math.PI, -Math.PI / 5, Math.PI]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle005.geometry}
          material={materials.aluminium}
          position={[0.011, -0.478, -0.015]}
          rotation={[0, -1.257, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder013.geometry}
          material={materials["Noir-2"]}
          position={[0.016, -0.7, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder014.geometry}
          material={materials.Noir}
          position={[0.016, -0.7, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder015.geometry}
          material={materials["Noir-2"]}
          position={[0.016, -0.7, 0]}
          rotation={[0, 1.257, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder016.geometry}
          material={materials.Noir}
          position={[0.016, -0.7, 0]}
          rotation={[0, 1.257, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder017.geometry}
          material={materials["Noir-2"]}
          position={[0.016, -0.7, 0]}
          rotation={[-Math.PI, Math.PI / 5, -Math.PI]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder018.geometry}
          material={materials.Noir}
          position={[0.016, -0.7, 0]}
          rotation={[-Math.PI, Math.PI / 5, -Math.PI]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder019.geometry}
          material={materials["Noir-2"]}
          position={[0.016, -0.7, 0]}
          rotation={[Math.PI, -Math.PI / 5, Math.PI]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder020.geometry}
          material={materials.Noir}
          position={[0.016, -0.7, 0]}
          rotation={[Math.PI, -Math.PI / 5, Math.PI]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder021.geometry}
          material={materials["Noir-2"]}
          position={[0.016, -0.7, 0]}
          rotation={[0, -1.257, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder022.geometry}
          material={materials.Noir}
          position={[0.016, -0.7, 0]}
          rotation={[0, -1.257, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane257.geometry}
          material={materials.aluminium}
          position={[0.465, 0.447, -0.636]}
          rotation={[-0.1, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane258.geometry}
          material={materials["Material.Chair"]}
          position={[0.465, 0.437, -0.344]}
          rotation={[0.012, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane259.geometry}
          material={materials.aluminium}
          position={[0.465, 0.447, -0.636]}
          rotation={[-0.1, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane261.geometry}
          material={materials.aluminium}
          position={[-0.475, 0.447, -0.636]}
          rotation={[-0.1, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane262.geometry}
          material={materials["Material.Chair"]}
          position={[-0.475, 0.437, -0.344]}
          rotation={[0.012, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Siege002.geometry}
          material={materials["Material.Chair"]}
          position={[0, 0.643, -0.644]}
          rotation={[1.286, 0, 0]}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube.geometry}
        material={materials["Noir-2"]}
        position={[-3.655, 2.194, -0.518]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane.geometry}
        material={materials["keybordkey.001"]}
        position={[-3.449, 2.267, -0.197]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane001.geometry}
        material={materials.keybordkey}
        position={[-3.449, 2.265, -0.197]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube001.geometry}
        material={materials.MaterialScrabble}
        position={[0, 1.51, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube002.geometry}
        material={materials["Material Monopoly"]}
        position={[0, 1.629, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder005.geometry}
        material={materials.aluminium}
        position={[3.567, 1.652, -2.838]}
        rotation={[-0.373, -1.028, -0.361]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder006.geometry}
        material={materials["blanc.001"]}
        position={[3.511, 3.823, -2.848]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder007.geometry}
        material={materials.aluminium}
        position={[3.385, 1.402, -2.838]}
        rotation={[-2.013, 1.395, 2.049]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder008.geometry}
        material={materials.aluminium}
        position={[3.672, 1.645, -2.838]}
        rotation={[-2.893, -0.49, 3.125]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder.geometry}
        material={materials.bleu}
        position={[-3.198, 1.388, 4.207]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder001.geometry}
        material={nodes.Cylinder001.material}
        position={[-3.654, 1.128, 2.684]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder002.geometry}
        material={materials["Material.009"]}
        position={[-3.786, 1.128, 3.194]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder003.geometry}
        material={materials["Material.009"]}
        position={[-3.242, 1.128, 2.784]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder004.geometry}
        material={materials["Material.009"]}
        position={[-3.306, 1.128, 3.265]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder023.geometry}
        material={materials["Noir-2"]}
        position={[-3.198, 1.388, 4.207]}
      />
      <group position={[-3.165, 1.427, 4.186]}>
        <group position={[-0.055, -0.064, 0.032]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["Plant_Areca_A_spring-summer-autumn_2"].geometry}
            material={materials.Leaf_Areca_bqm}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["Plant_Areca_A_spring-summer-autumn_3"].geometry}
            material={materials.Stem_Areca_bqm}
          />
        </group>
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube011.geometry}
        material={materials["Noir-2"]}
        position={[-2.403, 3.838, -3.22]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tableau002.geometry}
        material={materials["Peinture.001"]}
        position={[-2.403, 3.838, -3.22]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane263.geometry}
        material={materials["Noir-2"]}
        position={[-4.197, 4.101, 0.21]}
        rotation={[0, 0, -Math.PI / 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tableau001.geometry}
        material={materials["Material.001"]}
        position={[-4.197, 4.101, 0.21]}
        rotation={[-Math.PI, 0, Math.PI / 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Bottle.geometry}
        material={materials.Material}
        position={[3.522, 2.138, 3.47]}
        rotation={[0, 1.241, 0]}
        scale={1.026}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Container.geometry}
        material={materials.Rum}
        position={[3.523, 2.188, 3.47]}
        rotation={[0, 1.241, 0]}
        scale={0.884}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Foil.geometry}
        material={materials.foil}
        position={[3.522, 2.138, 3.47]}
        rotation={[0, 1.241, 0]}
        scale={1.026}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.LitubaDos.geometry}
        material={materials.LitubaDos}
        position={[3.358, 2.346, 3.413]}
        rotation={[Math.PI / 2, 0, 1.9]}
        scale={0.293}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Litutu2.geometry}
        material={materials.Litutu2}
        position={[3.523, 2.289, 3.47]}
        rotation={[0, 1.241, 0]}
        scale={1.821}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Litutufoil.geometry}
        material={materials.Litutufoil}
        position={[3.58, 2.588, 3.489]}
        rotation={[1.559, 0.035, -1.241]}
        scale={[0.097, 0.083, 0.101]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Bottle001.geometry}
        material={materials.Glass}
        position={[3.554, 2.153, 3.942]}
        rotation={[Math.PI, -0.977, 3.136]}
        scale={1.864}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Bottle_Label.geometry}
          material={materials["Glass Label"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Bottle_Label_Cap.geometry}
          material={materials["Material.004"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cap.geometry}
          material={materials.Cap}
          position={[0.002, 0.003, 0]}
          rotation={[0, 0, 0.006]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Liquid.geometry}
          material={materials.Liquid}
          rotation={[0, 0, 0.006]}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Bottle_Label_Back001.geometry}
        material={materials.BottleLabelBackMterial}
        position={[3.555, 2.153, 3.943]}
        rotation={[Math.PI, -0.977, 3.136]}
        scale={1.864}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle008.geometry}
        material={materials["Material.030"]}
        position={[0.01, 4.487, -3.3]}
        rotation={[Math.PI / 2, -Math.PI / 6, 0]}
      />
      <group position={[-3.582, 2.232, 0.258]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.soda_can_1.geometry}
          material={materials["Default OBJ"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.soda_can_2.geometry}
          material={materials["Material.008"]}
        />
      </group>
      <group position={[-3.918, 2.232, -0.421]} rotation={[0, 1.308, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.uploads_files_910687_mario_stl.geometry}
          material={materials.BlancMario}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.uploads_files_910687_mario_stl_1.geometry}
          material={materials.BleuMario}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.uploads_files_910687_mario_stl_2.geometry}
          material={materials["Material.010"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.uploads_files_910687_mario_stl_3.geometry}
          material={materials["Material.011"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.uploads_files_910687_mario_stl_4.geometry}
          material={materials["Material.014"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.uploads_files_910687_mario_stl_5.geometry}
          material={materials["Material.021"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.uploads_files_910687_mario_stl_6.geometry}
          material={materials["Material.022"]}
        />
      </group>
      <group
        position={[-3.863, 2.151, -1.645]}
        rotation={[Math.PI / 2, 0, -0.793]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object1_1.geometry}
          material={materials["0.003922_0.003922_0.003922_0.000000"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object1_2.geometry}
          material={materials["CHROME.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object1_3.geometry}
          material={materials.plast}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object1_4.geometry}
          material={materials.dark}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object1_5.geometry}
          material={materials.black_gloss}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object1_6.geometry}
          material={materials.apple}
        />
      </group>
      <group
        position={[-3.373, 2.223, 0.427]}
        rotation={[Math.PI / 2, 0, -2.38]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.stapler001_1.geometry}
          material={materials["Default OBJ.004"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.stapler001_2.geometry}
          material={materials.aluminium}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pen_tidy.geometry}
        material={materials["Default OBJ.005"]}
        position={[-3.993, 2.234, -0.214]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pencil.geometry}
        material={materials["Default OBJ.006"]}
        position={[-3.994, 2.352, -0.247]}
        rotation={[3.131, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.sticky_note_pad.geometry}
        material={materials["Default OBJ.001"]}
        position={[-3.577, 2.32, -1.071]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={1.462}
      />
      <group
        position={[0, 1.468, 0.531]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={1.318}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.book_01_1.geometry}
          material={materials["Default OBJ.003"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.book_01_2.geometry}
          material={materials["Material.029"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/model/Room.glb");
